import { Destination, Category, Experience, Vendor, ExperienceCategory, Difficulty, PricePer, ExperienceStatus } from './types'

export const destinations: Destination[] = [
  {
    id: 'dest_bali',
    name: 'Bali',
    country: 'Indonesia',
    tagline: 'Island of the Gods',
    heroImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&h=600&fit=crop',
    currency: 'USD',
    timezone: 'Asia/Makassar',
    active: true,
  },
  {
    id: 'dest_phuket',
    name: 'Phuket',
    country: 'Thailand',
    tagline: 'Pearl of the Andaman',
    heroImage: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=1200&h=600&fit=crop',
    currency: 'USD',
    timezone: 'Asia/Bangkok',
    active: false,
  },
  {
    id: 'dest_maldives',
    name: 'Maldives',
    country: 'Maldives',
    tagline: 'Paradise Islands',
    heroImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&h=600&fit=crop',
    currency: 'USD',
    timezone: 'Indian/Maldives',
    active: false,
  },
  {
    id: 'dest_santorini',
    name: 'Santorini',
    country: 'Greece',
    tagline: 'Aegean Jewel',
    heroImage: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1200&h=600&fit=crop',
    currency: 'EUR',
    timezone: 'Europe/Athens',
    active: false,
  },
]

export const categories: Category[] = [
  {
    id: ExperienceCategory.WaterAdventures,
    name: 'Water Adventures',
    icon: 'waves',
    tagline: 'Boat trips, snorkeling, diving',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop',
  },
  {
    id: ExperienceCategory.LandExplorations,
    name: 'Land Explorations',
    icon: 'bicycle',
    tagline: 'Bikes, scooters, guided treks',
    image: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&h=600&fit=crop',
  },
  {
    id: ExperienceCategory.CultureExperiences,
    name: 'Culture & Experiences',
    icon: 'temple',
    tagline: 'Temples, ceremonies, cooking classes',
    image: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&h=600&fit=crop',
  },
  {
    id: ExperienceCategory.FoodNightlife,
    name: 'Food & Nightlife',
    icon: 'utensils',
    tagline: 'Local warungs to beach clubs',
    image: 'https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=800&h=600&fit=crop',
  },
  {
    id: ExperienceCategory.Transportation,
    name: 'Getting Around',
    icon: 'car',
    tagline: 'Transfers, drivers, day trips',
    image: 'https://images.unsplash.com/photo-1586339277861-560376e85e32?w=800&h=600&fit=crop',
  },
  {
    id: ExperienceCategory.Stays,
    name: 'Destinations & Stays',
    icon: 'home',
    tagline: 'Where will you wake up?',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&h=600&fit=crop',
  },
]

export const experiences: Experience[] = [
  {
    id: 'exp_001',
    title: 'Sunrise Snorkeling at Menjangan Island',
    category: ExperienceCategory.WaterAdventures,
    subcategory: 'snorkeling',
    destination: 'dest_bali',
    provider: {
      id: 'prov_001',
      name: "Wayan's Dive Shop",
      photo: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=200&h=200&fit=crop',
      bio: "Wayan learned to freedive from his father at age 7 in the waters off Lovina. After working as a dive instructor across Indonesia for 15 years, he returned home to start his own operation with his wife Ketut.",
      since: 1998,
      rating: 4.9,
      reviewCount: 127,
      responseTime: 'within 2 hours',
      verified: true,
      instantBookEnabled: true,
    },
    price: {
      amount: 65,
      currency: 'USD',
      per: PricePer.Person,
    },
    duration: '6 hours',
    durationHours: 6,
    startTime: '05:00',
    groupSize: { min: 2, max: 8 },
    difficulty: Difficulty.Easy,
    languages: ['English', 'Indonesian'],
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1682687220795-796d3f6f7000?w=1200&h=800&fit=crop',
    ],
    description: "You'll meet your guide at dawn as the fishing boats head out to sea. The 90-minute boat ride to Menjangan Island is an adventure in itself, with dolphins often joining alongside.\n\nThe water at this hour is impossibly calm, and as you slip beneath the surface, you'll discover a coral garden that few tourists ever see. Your guide knows exactly where the sea turtles rest and where the colorful schools gather.\n\nAfter two snorkeling sessions at different spots, you'll enjoy a traditional Balinese breakfast on the boat as the sun climbs higher. The return journey offers stunning views of Bali's volcanic coastline.",
    included: [
      'Hotel pickup & drop-off (Lovina, Pemuteran areas)',
      'Professional snorkeling equipment',
      'Licensed English-speaking guide',
      'Traditional Balinese breakfast',
      'Underwater photos sent same day',
      'Towels and dry bag',
    ],
    notIncluded: [
      'Tips for boat crew (suggested: 50,000 IDR)',
      'Marine park entrance fee (25,000 IDR, paid on arrival)',
    ],
    meetingPoint: {
      name: 'Lovina Beach Harbor',
      address: 'Jl. Raya Lovina, Kalibukbuk, Buleleng',
      lat: -8.1592,
      lng: 115.0449,
      instructions: "Look for the blue boat with 'Wayan's Dive' painted on the side. Wayan will be waiting with hot coffee.",
    },
    cancellation: 'Free cancellation up to 24 hours before. Full refund, no questions asked.',
    whatToBring: ['Sunscreen (reef-safe please!)', 'Swimwear', 'Camera', 'Light jacket for morning'],
    reviews: [
      {
        id: 'rev_001',
        author: 'Sarah',
        country: 'AU',
        date: '2024-12-15',
        rating: 5,
        text: "Absolutely magical experience! Wayan knew exactly where to find the turtles. The breakfast on the boat was such a nice touch. Highly recommend getting the photos - the underwater shots are incredible.",
        helpful: 23,
      },
      {
        id: 'rev_002',
        author: 'Marcus',
        country: 'DE',
        date: '2024-12-08',
        rating: 5,
        text: "Best snorkeling I've done in Southeast Asia. The coral here is pristine because it's protected. Early start was worth it - we had the reef almost to ourselves.",
        helpful: 18,
      },
      {
        id: 'rev_003',
        author: 'Jessica',
        country: 'US',
        date: '2024-11-28',
        rating: 4,
        text: "Great experience overall. The boat ride is long but comfortable. Saw so many fish! Only giving 4 stars because we didn't see dolphins on our trip, but that's just luck.",
        helpful: 7,
      },
    ],
    tags: ['beginner', 'fullday', 'toprated'],
  },
  {
    id: 'exp_002',
    title: 'Sunrise Mount Batur Volcano Trek',
    category: 'land_explorations',
    subcategory: 'hiking',
    destination: 'dest_bali',
    provider: {
      id: 'prov_002',
      name: 'Batur Mountain Guides Association',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      bio: 'The official association of Mount Batur guides, ensuring safe and authentic volcano experiences since 1995. All guides are local villagers who know every path and story of the sacred mountain.',
      since: 1995,
      rating: 4.8,
      reviewCount: 342,
      responseTime: 'within 1 hour',
      verified: true,
      instantBookEnabled: true,
    },
    price: {
      amount: 55,
      currency: 'USD',
      per: 'person',
    },
    duration: '7 hours',
    startTime: '02:00',
    groupSize: { min: 1, max: 15 },
    difficulty: 'Moderate',
    languages: ['English', 'Indonesian', 'Japanese'],
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=1200&h=800&fit=crop',
    ],
    description: "The alarm will feel brutal at 1 AM, but trust us - this is worth every lost hour of sleep.\n\nYour guide picks you up in the darkness for the drive to Batur's base. The trek begins under starlight, with headlamps illuminating the volcanic soil path. Your guide shares stories of the mountain's 1963 eruption and its spiritual significance to Balinese Hindus.\n\nThe 2-hour climb is steady but achievable for anyone with moderate fitness. And then it happens - the sky begins to glow. Watching the sun rise over Mount Agung and Lake Batur from 1,717 meters is genuinely one of Bali's most profound moments.\n\nBreakfast is served at the summit: eggs cooked in volcanic steam, banana sandwiches, and hot drinks. After exploring the crater rim, you'll descend as the mountain reveals its dramatic moonscape in full daylight.",
    included: [
      'Hotel pickup & drop-off (Ubud, Sanur, Seminyak)',
      'Professional certified mountain guide',
      'Flashlight/headlamp',
      'Breakfast at summit',
      'Hot drinks',
      'Entrance fees',
    ],
    notIncluded: [
      'Tips for guide (suggested: 100,000 IDR)',
      'Personal trekking gear',
      'Travel insurance',
    ],
    meetingPoint: {
      name: 'Hotel pickup',
      instructions: 'Your guide will pick you up from your hotel lobby between 1:30-2:30 AM depending on your location.',
    },
    cancellation: 'Free cancellation up to 24 hours before. Cancellation required if heavy rain is forecast.',
    whatToBring: ["Warm layers (it's cold at the top!)", 'Good walking shoes', 'Camera', 'Water bottle'],
    reviews: [
      {
        id: 'rev_004',
        author: 'Tom',
        country: 'UK',
        date: '2024-12-10',
        rating: 5,
        text: 'Absolutely stunning. The early wake-up is tough but completely worth it. Our guide was knowledgeable and kept a good pace.',
        helpful: 31,
      },
      {
        id: 'rev_005',
        author: 'Lily',
        country: 'CA',
        date: '2024-11-30',
        rating: 5,
        text: 'One of the highlights of our Bali trip. The sunrise was breathtaking and the eggs cooked in volcanic steam were a fun touch!',
        helpful: 19,
      },
    ],
    tags: ['fullday', 'toprated'],
  },
  {
    id: 'exp_003',
    title: 'Traditional Balinese Cooking Class in Village Home',
    category: 'culture_experiences',
    subcategory: 'cooking',
    destination: 'dest_bali',
    provider: {
      id: 'prov_003',
      name: "Ibu Mangku's Kitchen",
      photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
      bio: 'Ibu Mangku has been cooking traditional Balinese food for over 40 years. She learned from her grandmother and now shares these recipes with travelers in her family compound, just as her grandmother taught her.',
      since: 2010,
      rating: 4.9,
      reviewCount: 203,
      responseTime: 'within 4 hours',
      verified: true,
    },
    price: {
      amount: 45,
      currency: 'USD',
      per: 'person',
    },
    duration: '5 hours',
    startTime: '08:00',
    groupSize: { min: 2, max: 8 },
    difficulty: 'Easy',
    languages: ['English', 'Indonesian'],
    images: [
      'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=1200&h=800&fit=crop',
    ],
    description: "Begin your morning at the local market with Ibu Mangku, where she'll teach you to select the freshest ingredients while sharing stories of Balinese daily life.\n\nBack at her family compound in Ubud's outskirts, you'll discover an open-air kitchen where generations have prepared food for ceremonies and celebrations. Learn to grind your own spice pastes using traditional stone tools, wrap satay by hand, and master the balance of Balinese flavors.\n\nYou'll prepare 6-7 dishes including Lawar (traditional chopped meat salad), Sate Lilit (minced seafood satay), Pepes Ikan (fish wrapped in banana leaf), and Dadar Gulung (coconut pancakes). Then sit down with the family to enjoy everything you've made.\n\nRecipes and a small spice kit are included so you can recreate these dishes at home.",
    included: [
      'Hotel pickup & drop-off (Ubud area)',
      'Market tour with guide',
      'All ingredients and equipment',
      'Recipe booklet to take home',
      'Small spice kit souvenir',
      'Full meal of dishes prepared',
      'Water, tea, and coffee throughout',
    ],
    notIncluded: ['Alcoholic drinks', 'Personal purchases at market'],
    meetingPoint: {
      name: 'Hotel pickup',
      instructions: 'Pickup from Ubud area hotels at 8 AM. For locations outside Ubud, meeting at Ubud central.',
    },
    cancellation: 'Free cancellation up to 24 hours before.',
    whatToBring: ['Comfortable clothes', 'Appetite', 'Camera'],
    reviews: [
      {
        id: 'rev_006',
        author: 'Emma',
        country: 'NZ',
        date: '2024-12-05',
        rating: 5,
        text: "Ibu Mangku is a gem! Such a warm host and amazing cook. Learned so much and the food was delicious. Definitely doing these recipes at home.",
        helpful: 28,
      },
      {
        id: 'rev_007',
        author: 'David',
        country: 'US',
        date: '2024-11-22',
        rating: 5,
        text: 'Highlight of our trip! The market tour was fascinating and cooking in a real Balinese home was so authentic. The spice kit is a lovely souvenir.',
        helpful: 15,
      },
    ],
    tags: ['beginner', 'halfday', 'toprated', 'under50'],
  },
  {
    id: 'exp_004',
    title: 'Airport Pickup - Private Transfer to Ubud',
    category: 'transportation',
    subcategory: 'transfer',
    destination: 'dest_bali',
    provider: {
      id: 'prov_004',
      name: "Ketut's Bali Drivers",
      photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop',
      bio: "Ketut started driving tourists in 1990 with a borrowed car. Now his fleet of 12 comfortable vehicles and team of professional drivers provide safe, reliable transport across Bali.",
      since: 1990,
      rating: 4.7,
      reviewCount: 89,
      responseTime: 'within 30 minutes',
      verified: true,
    },
    price: {
      amount: 25,
      currency: 'USD',
      per: 'vehicle',
    },
    duration: '1.5 hours',
    groupSize: { min: 1, max: 4 },
    difficulty: 'Easy',
    languages: ['English', 'Indonesian'],
    images: [
      'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1586339277861-560376e85e32?w=1200&h=800&fit=crop',
    ],
    description: "Skip the taxi queue and start your Bali trip stress-free. Your driver will be waiting in arrivals with your name sign, help with luggage, and provide a comfortable air-conditioned ride direct to your accommodation.\n\nCold water and WiFi available in vehicle. Driver can make a quick stop if you need to get cash or SIM card on the way.",
    included: [
      'Meet and greet in arrivals hall',
      'Air-conditioned private vehicle',
      'Bottled water',
      'In-car WiFi',
      'Flight monitoring (driver adjusts for delays)',
      'Child seat on request',
    ],
    notIncluded: ['Stop at attractions en route (available for extra fee)'],
    meetingPoint: {
      name: 'Ngurah Rai International Airport (DPS)',
      instructions: 'After exiting customs, look for your driver holding a sign with your name in the arrivals hall.',
    },
    cancellation: 'Free cancellation up to 12 hours before.',
    whatToBring: [],
    reviews: [
      {
        id: 'rev_008',
        author: 'Chris',
        country: 'SG',
        date: '2024-12-01',
        rating: 5,
        text: 'Easy and hassle-free. Driver was waiting right where he said he would be. Clean car and friendly service.',
        helpful: 12,
      },
    ],
    tags: ['under50', 'private'],
  },
  {
    id: 'exp_005',
    title: 'Full Day Nusa Penida Island Adventure',
    category: 'water_adventures',
    subcategory: 'island_tour',
    destination: 'dest_bali',
    provider: {
      id: 'prov_005',
      name: 'Penida Island Tours',
      photo: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=200&h=200&fit=crop',
      bio: 'Local guides born and raised on Nusa Penida, sharing the hidden gems and dramatic landscapes of their island home with small groups.',
      since: 2015,
      rating: 4.8,
      reviewCount: 215,
      responseTime: 'within 3 hours',
      verified: true,
    },
    price: {
      amount: 85,
      currency: 'USD',
      per: 'person',
    },
    duration: '10 hours',
    startTime: '07:00',
    groupSize: { min: 4, max: 12 },
    difficulty: 'Moderate',
    languages: ['English', 'Indonesian'],
    images: [
      'https://images.unsplash.com/photo-1559628376-f3fe5f782a2e?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1583012239766-8c2c93e68d20?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606158911056-e9445e4312ad?w=1200&h=800&fit=crop',
    ],
    description: "Escape to one of Bali's most dramatic islands for a day of jaw-dropping coastal scenery. The fast boat ride to Nusa Penida takes 45 minutes, cutting through turquoise waters.\n\nYour guide will take you to the island's most iconic spots: Kelingking Beach (T-Rex cliff), Angel's Billabong natural infinity pool, Broken Beach's natural archway, and Crystal Bay for swimming. The landscapes here are unlike anywhere else in Bali - rugged, dramatic, and incredibly photogenic.\n\nLunch is included at a local warung with ocean views. Be prepared for some adventurous roads and stairs, but the views are absolutely worth it.",
    included: [
      'Hotel pickup & drop-off (Sanur, Seminyak, Ubud)',
      'Fast boat tickets round trip',
      'Private car and driver on Nusa Penida',
      'English-speaking guide',
      'Lunch at local restaurant',
      'Entrance fees to all sites',
      'Snorkeling equipment',
    ],
    notIncluded: ['Drinks and snacks', 'Tips for guide and driver'],
    meetingPoint: {
      name: 'Hotel pickup',
      instructions: 'Pickup from hotel between 6:30-7:30 AM depending on location.',
    },
    cancellation: 'Free cancellation up to 48 hours before due to boat booking.',
    whatToBring: ['Swimwear', 'Sunscreen', 'Good walking shoes', 'Camera', 'Water bottle'],
    reviews: [
      {
        id: 'rev_009',
        author: 'Sophie',
        country: 'FR',
        date: '2024-12-12',
        rating: 5,
        text: "Incredible day! Kelingking Beach viewpoint is absolutely stunning. The boat ride was smooth and our guide was fantastic. Long day but worth every minute.",
        helpful: 34,
      },
      {
        id: 'rev_010',
        author: 'James',
        country: 'AU',
        date: '2024-11-28',
        rating: 4,
        text: 'Amazing scenery and well-organized tour. Be prepared for lots of stairs and some rough roads. Bring motion sickness tablets for the boat if you need them.',
        helpful: 22,
      },
    ],
    tags: ['fullday', 'toprated', 'group'],
  },
  {
    id: 'exp_006',
    title: 'Beginner Scuba Diving Discover Course',
    category: 'water_adventures',
    subcategory: 'diving',
    destination: 'dest_bali',
    provider: {
      id: 'prov_006',
      name: 'Tulamben Dive Center',
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
      bio: 'PADI 5-star dive center specializing in beginner courses and the famous USAT Liberty shipwreck. Safety-first approach with experienced instructors.',
      since: 2005,
      rating: 4.9,
      reviewCount: 178,
      responseTime: 'within 2 hours',
      verified: true,
    },
    price: {
      amount: 120,
      currency: 'USD',
      per: 'person',
    },
    duration: '8 hours',
    startTime: '08:00',
    groupSize: { min: 1, max: 4 },
    difficulty: 'Beginner-friendly',
    languages: ['English', 'Indonesian', 'Mandarin'],
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1682687220801-eef408f95d71?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1682687221038-404cb8830901?w=1200&h=800&fit=crop',
    ],
    description: "Always wanted to try scuba diving? This is your perfect introduction. Start with pool training where you'll learn basic skills in shallow water with patient instructors. Once comfortable, you'll make two open water dives at the famous USAT Liberty shipwreck in Tulamben.\n\nThis World War II cargo ship, torpedoed in 1942, now rests in 5-30 meters of water and is covered in vibrant coral. It's one of the world's most accessible wreck dives - you can swim to it directly from the beach.\n\nNo certification required, no prior experience needed. Just curiosity and a sense of adventure. Who knows, this might be the start of a lifelong passion.",
    included: [
      'Hotel pickup & drop-off',
      'Professional PADI instructor (max 4 students per instructor)',
      'All scuba equipment rental',
      'Two guided dives',
      'Pool training session',
      'Lunch and refreshments',
      'Underwater photos',
    ],
    notIncluded: ['Dive certification (this is a try-dive, not certification course)', 'Personal dive computer'],
    meetingPoint: {
      name: 'Hotel pickup',
      instructions: 'Pickup from East Bali hotels. Surcharge for pickup from Ubud/Seminyak.',
    },
    cancellation: 'Free cancellation up to 48 hours before.',
    whatToBring: ['Swimwear', 'Towel', 'Change of clothes', 'Sense of adventure'],
    reviews: [
      {
        id: 'rev_011',
        author: 'Rachel',
        country: 'US',
        date: '2024-12-08',
        rating: 5,
        text: "First time diving and it was incredible! The instructors were so patient and made me feel completely safe. The shipwreck is amazing - saw so many fish!",
        helpful: 29,
      },
    ],
    tags: ['beginner', 'fullday', 'toprated', 'private'],
  },
  {
    id: 'exp_007',
    title: 'Surfing Lesson in Canggu',
    category: 'water_adventures',
    subcategory: 'surfing',
    destination: 'dest_bali',
    provider: {
      id: 'prov_007',
      name: 'Canggu Surf School',
      photo: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=200&h=200&fit=crop',
      bio: 'Professional surf instructors teaching beginners and intermediate surfers since 2012. Small groups ensure personalized attention and faster progress.',
      since: 2012,
      rating: 4.7,
      reviewCount: 156,
      responseTime: 'within 1 hour',
      verified: true,
    },
    price: {
      amount: 40,
      currency: 'USD',
      per: 'person',
    },
    duration: '2 hours',
    startTime: '08:00',
    groupSize: { min: 1, max: 6 },
    difficulty: 'Beginner-friendly',
    languages: ['English', 'Indonesian'],
    images: [
      'https://images.unsplash.com/photo-1502933691298-84fc14542831?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1621883863991-1cd7e7b838be?w=1200&h=800&fit=crop',
    ],
    description: "Canggu's gentle waves are perfect for learning to surf. Your instructor will start with beach technique - how to pop up, paddle, and read the waves. Then it's into the water for practice.\n\nMost beginners catch their first wave within the first hour. By the end of the session, you'll have the basics down and a huge smile on your face. The stoke is real.",
    included: ['Surfboard rental', 'Rash guard', 'Professional instructor', 'Beach shower access'],
    notIncluded: ['Photos (available for purchase)', 'Transportation'],
    meetingPoint: {
      name: 'Batu Bolong Beach, Canggu',
      address: 'Jl. Pantai Batu Bolong, Canggu',
      instructions: 'Meet at the surf school hut with blue and yellow umbrellas.',
    },
    cancellation: 'Free cancellation up to 24 hours before.',
    whatToBring: ['Swimwear', 'Sunscreen', 'Towel', 'Positive attitude'],
    reviews: [
      {
        id: 'rev_012',
        author: 'Mike',
        country: 'UK',
        date: '2024-12-14',
        rating: 5,
        text: 'Great intro to surfing! Instructor was encouraging and gave really helpful tips. Stood up on my third wave!',
        helpful: 18,
      },
    ],
    tags: ['beginner', 'halfday', 'under50'],
  },
  {
    id: 'exp_008',
    title: 'Bicycle Tour Through Rice Terraces',
    category: 'land_explorations',
    subcategory: 'cycling',
    destination: 'dest_bali',
    provider: {
      id: 'prov_008',
      name: 'Ubud Cycling Adventures',
      photo: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=200&h=200&fit=crop',
      bio: 'Small-group cycling tours through traditional villages and rice terraces, led by local guides who share insights into Balinese rural life.',
      since: 2008,
      rating: 4.8,
      reviewCount: 189,
      responseTime: 'within 2 hours',
      verified: true,
    },
    price: {
      amount: 45,
      currency: 'USD',
      per: 'person',
    },
    duration: '4 hours',
    startTime: '07:00',
    groupSize: { min: 2, max: 10 },
    difficulty: 'Easy',
    languages: ['English', 'Indonesian'],
    images: [
      'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1580735960274-3bf47a5b1a7f?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1589811828791-be878d1d09c8?w=1200&h=800&fit=crop',
    ],
    description: "Cycle downhill through some of Bali's most beautiful countryside. Start high in the hills and coast through emerald rice terraces, past family compounds, and through quiet villages.\n\nYour guide stops frequently to explain the rice growing process, traditional architecture, and daily village life. Visit a local home, see how coconut oil is made, and stop at a coffee plantation.\n\nThe route is mostly downhill and suitable for all fitness levels. Finish with a traditional Balinese lunch overlooking the rice fields.",
    included: [
      'Hotel pickup & drop-off (Ubud, Sanur, Seminyak)',
      'Quality mountain bike and helmet',
      'Support vehicle following group',
      'English-speaking guide',
      'Balinese lunch',
      'Bottled water and snacks',
      'Village visits and demonstrations',
    ],
    notIncluded: ['Personal expenses', 'Tips'],
    meetingPoint: {
      name: 'Hotel pickup',
      instructions: 'Pickup from hotel between 6:30-7:30 AM.',
    },
    cancellation: 'Free cancellation up to 24 hours before.',
    whatToBring: ['Comfortable clothes', 'Closed-toe shoes', 'Sunscreen', 'Camera'],
    reviews: [
      {
        id: 'rev_013',
        author: 'Laura',
        country: 'NL',
        date: '2024-12-11',
        rating: 5,
        text: 'Beautiful morning cycling through the rice terraces. Our guide was knowledgeable and the pace was relaxed. Perfect way to see rural Bali!',
        helpful: 25,
      },
    ],
    tags: ['beginner', 'halfday', 'under50', 'toprated', 'group'],
  },
  {
    id: 'exp_009',
    title: 'Scooter Rental - Full Day',
    category: 'transportation',
    subcategory: 'rental',
    destination: 'dest_bali',
    provider: {
      id: 'prov_009',
      name: 'Bali Bike Rentals',
      photo: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=200&h=200&fit=crop',
      bio: 'Well-maintained scooters and motorcycles for rent with helmet, insurance, and 24/7 roadside assistance included.',
      since: 2010,
      rating: 4.6,
      reviewCount: 432,
      responseTime: 'within 1 hour',
      verified: true,
    },
    price: {
      amount: 8,
      currency: 'USD',
      per: 'day',
    },
    duration: '24 hours',
    groupSize: { min: 1, max: 1 },
    difficulty: 'Easy',
    languages: ['English', 'Indonesian'],
    images: [
      'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1586339277861-560376e85e32?w=1200&h=800&fit=crop',
    ],
    description: "Freedom to explore Bali at your own pace. Our scooters are serviced regularly and come with helmets, basic insurance, and roadside assistance.\n\nPick up from our shop or we can deliver to your hotel for a small fee. Return the next day or extend for multiple days at discounted rates.",
    included: ['Helmet', 'Basic insurance', '24/7 roadside assistance', 'Full tank of fuel'],
    notIncluded: ['Fuel refill', 'International driving permit (required by law)', 'Delivery fee if applicable'],
    meetingPoint: {
      name: 'Bali Bike Rentals Shop',
      address: 'Jl. Raya Seminyak No. 42, Seminyak',
      instructions: 'Come to our shop with your license and passport. Or request hotel delivery.',
    },
    cancellation: 'Free cancellation up to 24 hours before.',
    whatToBring: ['Valid driving license', 'International driving permit', 'Passport or ID'],
    reviews: [
      {
        id: 'rev_014',
        author: 'Alex',
        country: 'AU',
        date: '2024-12-09',
        rating: 5,
        text: 'Great bikes in good condition. Staff was friendly and helpful with route suggestions. Best way to see Bali!',
        helpful: 16,
      },
    ],
    tags: ['under50', 'private'],
  },
  {
    id: 'exp_010',
    title: 'Ubud Art Market & Temples Walking Tour',
    category: 'culture_experiences',
    subcategory: 'walking_tour',
    destination: 'dest_bali',
    provider: {
      id: 'prov_010',
      name: 'Ubud Heritage Walks',
      photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
      bio: 'Local historians and cultural guides sharing the stories and traditions of Ubud through intimate walking tours.',
      since: 2013,
      rating: 4.8,
      reviewCount: 167,
      responseTime: 'within 3 hours',
      verified: true,
    },
    price: {
      amount: 30,
      currency: 'USD',
      per: 'person',
    },
    duration: '3 hours',
    startTime: '09:00',
    groupSize: { min: 2, max: 8 },
    difficulty: 'Easy',
    languages: ['English', 'Indonesian'],
    images: [
      'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1580735960274-3bf47a5b1a7f?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1512100356356-de1b84283e18?w=1200&h=800&fit=crop',
    ],
    description: "Explore the heart of Ubud on foot with a local guide. Start at the bustling art market where you'll learn bargaining techniques and discover traditional crafts. Your guide explains the significance of different items and introduces you to artisan vendors.\n\nContinue to Ubud Palace and the sacred Saraswati Temple with its beautiful lotus pond. Learn about Balinese Hinduism, daily offerings, and temple etiquette. Walk through quiet neighborhood streets to see how locals actually live.\n\nA gentle-paced tour perfect for getting oriented to Ubud and understanding Balinese culture.",
    included: [
      'English-speaking local guide',
      'Temple entrance fees',
      'Welcome drink',
      'Bottled water',
      'Small souvenir from market',
    ],
    notIncluded: ['Personal shopping', 'Lunch'],
    meetingPoint: {
      name: 'Ubud Royal Palace',
      address: 'Jl. Raya Ubud No.8, Ubud',
      instructions: 'Meet your guide at the main entrance of Ubud Palace.',
    },
    cancellation: 'Free cancellation up to 24 hours before.',
    whatToBring: ['Comfortable walking shoes', 'Sun protection', 'Camera', 'Respectful clothing (covered shoulders/knees for temples)'],
    reviews: [
      {
        id: 'rev_015',
        author: 'Maria',
        country: 'ES',
        date: '2024-12-06',
        rating: 5,
        text: 'Wonderful introduction to Ubud! Our guide was so knowledgeable and passionate about Balinese culture. Learned so much in just 3 hours.',
        helpful: 21,
      },
    ],
    tags: ['beginner', 'halfday', 'under50', 'group'],
  },
  {
    id: 'exp_011',
    title: 'Traditional Kecak Fire Dance Performance',
    category: 'culture_experiences',
    subcategory: 'performance',
    destination: 'dest_bali',
    provider: {
      id: 'prov_011',
      name: 'Uluwatu Temple Cultural Center',
      photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop',
      bio: 'Preserving and performing traditional Balinese dance at the stunning clifftop Uluwatu Temple since 1975.',
      since: 1975,
      rating: 4.7,
      reviewCount: 298,
      responseTime: 'within 2 hours',
      verified: true,
    },
    price: {
      amount: 15,
      currency: 'USD',
      per: 'person',
    },
    duration: '1.5 hours',
    startTime: '18:00',
    groupSize: { min: 1, max: 200 },
    difficulty: 'Easy',
    languages: ['English', 'Indonesian'],
    images: [
      'https://images.unsplash.com/photo-1580709840101-ec78c1e7372e?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1554222311-aa7c14bc5cce?w=1200&h=800&fit=crop',
    ],
    description: "Watch the mesmerizing Kecak fire dance at sunset in one of Bali's most spectacular settings - clifftop Uluwatu Temple overlooking the Indian Ocean.\n\nThe Kecak tells the story of Ramayana through chanting by 50+ shirtless male dancers sitting in concentric circles, creating hypnotic rhythms without any musical instruments. As the sun sets behind the performers and monkeys play in the temple grounds, you'll witness one of Bali's most iconic cultural experiences.\n\nArrive early to explore the temple grounds and secure good seating for the performance.",
    included: ['Kecak dance performance ticket', 'Temple entrance fee', 'Performance program/guide'],
    notIncluded: ['Transportation to Uluwatu', 'Sarong rental (required for temple, 10,000 IDR)'],
    meetingPoint: {
      name: 'Uluwatu Temple',
      address: 'Pecatu, South Kuta, Badung',
      instructions: 'Purchase tickets at temple entrance. Performance starts at 6 PM. Arrive by 5:30 PM for temple visit and seating.',
    },
    cancellation: 'Tickets non-refundable but can be used any day.',
    whatToBring: ['Camera', 'Sarong for temple entry', 'Light jacket (can be windy on cliff)'],
    reviews: [
      {
        id: 'rev_016',
        author: 'John',
        country: 'US',
        date: '2024-12-13',
        rating: 5,
        text: 'Absolutely incredible performance in a stunning location. The sunset timing was perfect. Get there early for good seats!',
        helpful: 42,
      },
    ],
    tags: ['beginner', 'under50', 'toprated'],
  },
  {
    id: 'exp_012',
    title: 'Finn Beach Club Day Pass',
    category: 'food_nightlife',
    subcategory: 'beach_club',
    destination: 'dest_bali',
    provider: {
      id: 'prov_012',
      name: "Finn's Beach Club",
      photo: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=200&h=200&fit=crop',
      bio: "Bali's most iconic beach club offering stunning ocean views, infinity pool, world-class dining, and unforgettable sunsets.",
      since: 2016,
      rating: 4.6,
      reviewCount: 523,
      responseTime: 'within 1 hour',
      verified: true,
    },
    price: {
      amount: 50,
      currency: 'USD',
      per: 'person',
    },
    duration: '6 hours',
    startTime: '12:00',
    groupSize: { min: 1, max: 50 },
    difficulty: 'Easy',
    languages: ['English', 'Indonesian'],
    images: [
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&h=800&fit=crop',
    ],
    description: "Spend the day in paradise at Finn's Beach Club, perched on the clifftops of Uluwatu. Lounge by the infinity pool overlooking the Indian Ocean, enjoy world-class cocktails, and watch one of Bali's best sunsets.\n\nYour day pass includes pool access, beach club lounger, and towel service. Full restaurant and bar menu available for purchase.",
    included: ['Infinity pool access', 'Beach club lounger', 'Towel service', '$25 food & beverage credit'],
    notIncluded: ['Food and drinks beyond credit', 'Transportation', 'Spa services'],
    meetingPoint: {
      name: "Finn's Beach Club",
      address: 'Jl. Pantai Selatan Gau, Ungasan',
      instructions: 'Check in at reception with your booking confirmation.',
    },
    cancellation: 'Free cancellation up to 48 hours before.',
    whatToBring: ['Swimwear', 'Sunscreen', 'Sunglasses', 'Camera for sunset'],
    reviews: [
      {
        id: 'rev_017',
        author: 'Anna',
        country: 'RU',
        date: '2024-12-10',
        rating: 5,
        text: 'Absolutely stunning location! Pool is beautiful, food was great, and the sunset was unforgettable. Worth every penny.',
        helpful: 38,
      },
    ],
    tags: ['halfday', 'toprated'],
  },
  {
    id: 'exp_013',
    title: 'Private Driver - Full Day Customizable',
    category: 'transportation',
    subcategory: 'driver',
    destination: 'dest_bali',
    provider: {
      id: 'prov_004',
      name: "Ketut's Bali Drivers",
      photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop',
      bio: "Professional drivers who know Bali inside out. Design your own itinerary or ask for suggestions.",
      since: 1990,
      rating: 4.8,
      reviewCount: 234,
      responseTime: 'within 30 minutes',
      verified: true,
    },
    price: {
      amount: 60,
      currency: 'USD',
      per: 'day',
    },
    duration: '10 hours',
    startTime: '08:00',
    groupSize: { min: 1, max: 6 },
    difficulty: 'Easy',
    languages: ['English', 'Indonesian'],
    images: [
      'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&h=800&fit=crop',
    ],
    description: "Your own private driver and comfortable car for the day. Create your own itinerary or ask your driver for recommendations - they know the best spots, hidden temples, and local warungs.\n\nPopular routes include: Ubud highlights (monkey forest, rice terraces, waterfalls), East Bali temples (Tirta Gangga, Lempuyang), or North Bali beaches. Your driver waits while you explore each location.\n\nFlexible timing and route. Stop anywhere for photos, bathroom breaks, or snacks. It's your day, your way.",
    included: [
      'Private air-conditioned vehicle',
      'English-speaking driver',
      'Fuel',
      'Parking fees',
      'Bottled water',
      'Up to 10 hours (overtime charged per hour)',
    ],
    notIncluded: ['Entrance fees to attractions', 'Meals', 'Tips for driver'],
    meetingPoint: {
      name: 'Hotel pickup',
      instructions: 'Driver picks you up from your hotel at agreed time.',
    },
    cancellation: 'Free cancellation up to 24 hours before.',
    whatToBring: ['Camera', 'Comfortable clothes', 'List of places you want to visit'],
    reviews: [
      {
        id: 'rev_018',
        author: 'Kevin',
        country: 'CA',
        date: '2024-12-07',
        rating: 5,
        text: 'Best way to see Bali! Our driver Ketut was amazing - knowledgeable, friendly, and took us to some hidden spots we never would have found ourselves.',
        helpful: 27,
      },
    ],
    tags: ['fullday', 'private', 'toprated'],
  },
  {
    id: 'exp_014',
    title: 'Tegalalang Rice Terrace & Jungle Swing',
    category: 'land_explorations',
    subcategory: 'sightseeing',
    destination: 'dest_bali',
    provider: {
      id: 'prov_014',
      name: 'Tegalalang Eco Tours',
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
      bio: 'Sustainable tourism supporting local rice farmers while providing Instagram-worthy experiences.',
      since: 2014,
      rating: 4.5,
      reviewCount: 412,
      responseTime: 'within 2 hours',
      verified: true,
    },
    price: {
      amount: 25,
      currency: 'USD',
      per: 'person',
    },
    duration: '3 hours',
    startTime: '09:00',
    groupSize: { min: 1, max: 20 },
    difficulty: 'Easy',
    languages: ['English', 'Indonesian'],
    images: [
      'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1552055568-3590dd346511?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1589811828791-be878d1d09c8?w=1200&h=800&fit=crop',
    ],
    description: "Visit Bali's most photographed rice terraces and swing over the jungle canopy. Walk through the stunning UNESCO-heritage rice terraces of Tegalalang, learning about traditional Subak irrigation system from local farmers.\n\nThen it's time for the famous jungle swings - soar over the palm trees and rice fields with the jungle as your backdrop. Multiple swings and photo spots available. Professional photos included.\n\nFinish with coffee and snacks at a terrace café overlooking the valley.",
    included: [
      'Rice terrace entrance fee',
      'Jungle swing access (multiple swings)',
      'Professional photos (20+ shots)',
      'Coffee/tea and snack',
      'Guide services',
    ],
    notIncluded: ['Transportation (easy to combine with private driver)', 'Additional food and drinks'],
    meetingPoint: {
      name: 'Tegalalang Rice Terrace Main Entrance',
      address: 'Jl. Raya Tegallalang, Tegallalang, Gianyar',
      instructions: 'Look for our booth at the main entrance.',
    },
    cancellation: 'Free cancellation up to 24 hours before.',
    whatToBring: ['Camera', 'Comfortable shoes for walking', 'Dress nicely for photos', 'Sunscreen'],
    reviews: [
      {
        id: 'rev_019',
        author: 'Mia',
        country: 'IT',
        date: '2024-12-11',
        rating: 4,
        text: 'Rice terraces are gorgeous! Swings were fun and photos came out great. Can get crowded but worth it for the views.',
        helpful: 19,
      },
    ],
    tags: ['beginner', 'halfday', 'under50', 'group'],
  },
  {
    id: 'exp_015',
    title: 'Waterfalls & Hidden Gems Tour',
    category: 'land_explorations',
    subcategory: 'nature',
    destination: 'dest_bali',
    provider: {
      id: 'prov_015',
      name: 'Hidden Bali Adventures',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      bio: 'Small group tours to the secret spots that most tourists miss. Supporting local communities through responsible tourism.',
      since: 2016,
      rating: 4.9,
      reviewCount: 187,
      responseTime: 'within 2 hours',
      verified: true,
    },
    price: {
      amount: 55,
      currency: 'USD',
      per: 'person',
    },
    duration: '8 hours',
    startTime: '08:00',
    groupSize: { min: 2, max: 8 },
    difficulty: 'Moderate',
    languages: ['English', 'Indonesian'],
    images: [
      'https://images.unsplash.com/photo-1520208422220-d12a3c588e6c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1484821582734-6c9c9c689e0d?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200&h=800&fit=crop',
    ],
    description: "Escape the tourist crowds and discover Bali's hidden waterfalls and secret spots. Visit 3-4 stunning waterfalls including Tukad Cepung (sunlight beams through the cave), Tibumana (perfect for swimming), and Kanto Lampo (unique tiered cascades).\n\nYour guide takes you to local villages, traditional markets, and viewpoints that aren't in the guidebooks. Swim in natural pools, explore jungle trails, and experience authentic Bali.\n\nSmall groups ensure a personalized experience and access to spots that big tour buses can't reach.",
    included: [
      'Hotel pickup & drop-off',
      'Private air-conditioned vehicle',
      'English-speaking guide',
      'All entrance fees',
      'Lunch at local warung',
      'Bottled water throughout day',
    ],
    notIncluded: ['Personal expenses', 'Tips'],
    meetingPoint: {
      name: 'Hotel pickup',
      instructions: 'Pickup from Ubud, Sanur, Seminyak areas between 7:30-8:30 AM.',
    },
    cancellation: 'Free cancellation up to 24 hours before.',
    whatToBring: ['Swimwear', 'Towel', 'Change of clothes', 'Water shoes or sandals', 'Waterproof bag for phone'],
    reviews: [
      {
        id: 'rev_020',
        author: 'Oliver',
        country: 'UK',
        date: '2024-12-09',
        rating: 5,
        text: 'Fantastic day out! The waterfalls were stunning and we had them almost to ourselves. Guide was brilliant - so much local knowledge. Highly recommend!',
        helpful: 33,
      },
    ],
    tags: ['fullday', 'toprated', 'group'],
  },
  {
    id: 'exp_016',
    title: 'Sunset Dinner Cruise',
    category: 'food_nightlife',
    subcategory: 'cruise',
    destination: 'dest_bali',
    provider: {
      id: 'prov_016',
      name: 'Bali Hai Cruises',
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
      bio: 'Luxury catamaran cruises offering unforgettable evenings on the water with world-class dining and entertainment.',
      since: 2000,
      rating: 4.7,
      reviewCount: 356,
      responseTime: 'within 3 hours',
      verified: true,
    },
    price: {
      amount: 95,
      currency: 'USD',
      per: 'person',
    },
    duration: '3 hours',
    startTime: '17:30',
    groupSize: { min: 2, max: 100 },
    difficulty: 'Easy',
    languages: ['English', 'Indonesian'],
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1566024287286-457247b70310?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop',
    ],
    description: "Set sail on a luxury catamaran for an unforgettable sunset experience. Cruise along Bali's stunning coastline while enjoying a gourmet international buffet dinner, unlimited drinks, and live entertainment.\n\nWatch the sky turn brilliant shades of orange and pink as the sun sets over the Indian Ocean. Dance to live music, relax on the deck with a cocktail, or simply take in the views.\n\nPerfect for couples, celebrations, or anyone who wants to experience Bali from a different perspective.",
    included: [
      'Hotel pickup & drop-off (Nusa Dua, Sanur, Seminyak)',
      'Welcome drink on boarding',
      'International buffet dinner',
      'Unlimited beverages (beer, wine, soft drinks)',
      'Live entertainment and DJ',
      'Sunset viewing from the deck',
    ],
    notIncluded: ['Premium cocktails and spirits', 'Photos (available for purchase)', 'Tips'],
    meetingPoint: {
      name: 'Benoa Harbor',
      instructions: 'Check in at Bali Hai Cruises terminal 30 minutes before departure.',
    },
    cancellation: 'Free cancellation up to 48 hours before.',
    whatToBring: ['Light jacket or shawl (can be breezy)', 'Camera', 'Appetite'],
    reviews: [
      {
        id: 'rev_021',
        author: 'Sophia',
        country: 'US',
        date: '2024-12-14',
        rating: 5,
        text: 'Magical evening! The sunset was spectacular, food was delicious, and the crew was so friendly. Perfect date night!',
        helpful: 41,
      },
    ],
    tags: ['toprated', 'group'],
  },
]

export const vendors: Vendor[] = [
  {
    id: 'prov_001',
    businessName: "Wayan's Dive Shop",
    businessEmail: 'wayan@divesbali.com',
    ownerFirstName: 'Wayan',
    ownerLastName: 'Surya',
    phone: '+62 812-3456-7890',
    sinceYear: 1998,
    verified: true,
    status: 'active',
    createdAt: '2024-01-15T08:00:00Z',
    photo: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=200&h=200&fit=crop',
    bio: "Wayan learned to freedive from his father at age 7 in the waters off Lovina. After working as a dive instructor across Indonesia for 15 years, he returned home to start his own operation with his wife Ketut.",
  },
  {
    id: 'prov_002',
    businessName: 'Bali Trekking Adventures',
    businessEmail: 'info@balitrekking.com',
    ownerFirstName: 'Made',
    ownerLastName: 'Putra',
    phone: '+62 813-9876-5432',
    sinceYear: 2010,
    verified: true,
    status: 'active',
    createdAt: '2024-02-20T10:30:00Z',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    bio: 'Made has been guiding treks on Mount Batur for over a decade, sharing his deep knowledge of Balinese culture and nature.',
  },
  {
    id: 'prov_demo',
    businessName: 'Demo Vendor Account',
    businessEmail: 'demo@vendor.pulau',
    ownerFirstName: 'Demo',
    ownerLastName: 'Vendor',
    phone: '+62 800-0000-0000',
    sinceYear: 2025,
    verified: true,
    status: 'active',
    createdAt: '2025-01-01T00:00:00Z',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
    bio: 'Demo vendor account for testing purposes.',
  },
]
